# Generated by Django 3.1.6 on 2021-03-12 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210226_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputbroadcast',
            name='author',
        ),
        migrations.RemoveField(
            model_name='outputbroadcast',
            name='input',
        ),
        migrations.AddField(
            model_name='inputbroadcast',
            name='broadcast',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.outputbroadcast'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inputbroadcast',
            name='key',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='inputbroadcast',
            name='url',
            field=models.URLField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='outputbroadcast',
            name='key',
            field=models.CharField(default='', max_length=128),
        ),
    ]
