# Generated by Django 3.1.6 on 2021-03-12 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210312_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputbroadcast',
            name='broadcast',
        ),
        migrations.AddField(
            model_name='outputbroadcast',
            name='broadcast',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.inputbroadcast'),
            preserve_default=False,
        ),
    ]
