# Generated by Django 3.1.6 on 2021-03-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210312_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outputbroadcast',
            old_name='broadcast',
            new_name='input_broadcast',
        ),
    ]
