# Generated by Django 3.1.6 on 2021-03-18 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20210312_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputbroadcast',
            name='url',
        ),
        migrations.AddField(
            model_name='inputbroadcast',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputbroadcast',
            name='name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
