# Generated by Django 3.1.6 on 2021-03-18 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210318_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputbroadcast',
            name='input_broadcast',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.inputbroadcast'),
        ),
    ]
