# Generated by Django 3.1.6 on 2021-04-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210318_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputbroadcast',
            name='type',
            field=models.IntegerField(choices=[(1, 'RTMP'), (2, 'RTSP')], default=1),
        ),
    ]
