# Generated by Django 3.1.6 on 2021-04-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_outputbroadcast_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputbroadcast',
            name='type',
        ),
        migrations.AddField(
            model_name='inputbroadcast',
            name='type',
            field=models.IntegerField(choices=[(1, 'RTMP'), (2, 'RTSP')], default=1),
        ),
    ]
