# Generated by Django 3.1.6 on 2021-05-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210416_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputbroadcast',
            name='bitrate',
            field=models.IntegerField(default=2300),
        ),
    ]
