# Generated by Django 3.1.6 on 2021-05-28 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_auto_20210506_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('resolution', models.IntegerField(choices=[(0, '1440p'), (1, '1080p'), (2, '720p'), (3, '480p'), (4, '360p')], default=0)),
                ('privacy', models.IntegerField(choices=[(0, 'public'), (1, 'private')], default=0)),
                ('user_credentials', models.JSONField(null=True)),
                ('name', models.CharField(max_length=128)),
                ('bitrate', models.IntegerField(default=20000)),
                ('is_active', models.BooleanField(default=False)),
                ('url', models.CharField(default='rtmp://a.rtmp.youtube.com/live2', max_length=128)),
                ('key', models.CharField(default='', max_length=128)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('input_broadcast', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.inputbroadcast')),
            ],
        ),
    ]
